`include "registerType.v"
`include "opcode.v"
`define RV64I
`define RV64M
`define RV64A
`define RV64F
`define RV64D
`include "subsets\RV64I.v"
`include "subsets\RV64M.v"
`include "subsets\RV64A.v"
`include "subsets\RV64F.v"
`include "subsets\RV64D.v"
