######################################################################
##
## Filename: ALU_test.udo
## Created on: Wed Oct 07 3:01:59 中国标准时间 2015
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
